// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {settings} from '../models';
import {upload} from '../models';

export function AuthStatus():Promise<main.AuthStatus>;

export function CancelUpload():Promise<void>;

export function GetSettings():Promise<settings.Settings>;

export function Login(arg1:main.LoginRequest):Promise<main.AuthStatus>;

export function Logout():Promise<void>;

export function PickFiles():Promise<Array<string>>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function StartUpload(arg1:main.UploadStartRequest):Promise<main.UploadStartResponse>;

export function UploadState():Promise<upload.JobState>;
