// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function CancelUpload() {
  return window['go']['main']['App']['CancelUpload']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartUpload(arg1) {
  return window['go']['main']['App']['StartUpload'](arg1);
}

export function UploadState() {
  return window['go']['main']['App']['UploadState']();
}
