// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Login(arg1:main.LoginRequest):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function SelectFile():Promise<string>;

export function Upload(arg1:main.UploadRequest):Promise<main.UploadResult>;
